[project]
name = "aya-book"
version = "0.1.0"
description = "The book of Aya"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-material>=9.5.46",
    "mkdocs>=1.6.1",
    "mkdocs-callouts>=1.14.1",
]
