[project]
name = "book"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "mkdocs-material>=9.5.46",
    "mkdocs>=1.6.1",
    "mkdocs-callouts>=1.14.1",
]
