[workspace]
members = ["kprobetcp", "kprobetcp-common", "kprobetcp-ebpf"]

resolver = "2"

default-members = ["kprobetcp", "kprobetcp-common"]

[workspace.package]
edition = "2024"

[profile.release.package.kprobetcp-ebpf]
debug = 2
codegen-units = 1
