[package]
name = "xdp-log-common"
version = "0.1.0"
edition.workspace = true

[features]
default = []
user = ["aya"]

[dependencies]
aya = { git = "https://github.com/aya-rs/aya", optional = true }

[lib]
path = "src/lib.rs"
