[workspace]
members = ["xdp-log", "xdp-log-common", "xdp-log-ebpf"]

resolver = "2"

default-members = ["xdp-log", "xdp-log-common"]

[profile.release.package.xdp-log-ebpf]
debug = 2
codegen-units = 1
